version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: open_banking_manning
      MYSQL_ROOT_HOST: '%'                           # Nombre de usuario (opcional)
    ports:
      - "33061:3306"  # Mapea el puerto 3306 del contenedor al puerto 3306 del host
    volumes:
      - mysql_data:/var/lib/mysql  # Monta los datos de MySQL en un volumen para persistencia


volumes:
  mysql_data: